// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTestAppBack.DataAccess;

#nullable disable

namespace MyTestAppBack.DataAccess.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20230224063000_AddDescriptionToSyrups")]
    partial class AddDescriptionToSyrups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("MyTestAppBack.Domain.Aggregates.CoffeeComposition", b =>
                {
                    b.Property<long>("CoffeeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CoffeeIngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoffeeTypeId", "CoffeeIngredientId");

                    b.HasIndex("CoffeeIngredientId");

                    b.ToTable("CoffeeCompositions");

                    b.HasData(
                        new
                        {
                            CoffeeTypeId = 9L,
                            CoffeeIngredientId = 1L,
                            Value = 50L
                        },
                        new
                        {
                            CoffeeTypeId = 9L,
                            CoffeeIngredientId = 3L,
                            Value = 150L
                        },
                        new
                        {
                            CoffeeTypeId = 9L,
                            CoffeeIngredientId = 16L,
                            Value = 50L
                        },
                        new
                        {
                            CoffeeTypeId = 8L,
                            CoffeeIngredientId = 1L,
                            Value = 50L
                        },
                        new
                        {
                            CoffeeTypeId = 8L,
                            CoffeeIngredientId = 3L,
                            Value = 50L
                        },
                        new
                        {
                            CoffeeTypeId = 8L,
                            CoffeeIngredientId = 16L,
                            Value = 50L
                        },
                        new
                        {
                            CoffeeTypeId = 1L,
                            CoffeeIngredientId = 1L,
                            Value = 50L
                        },
                        new
                        {
                            CoffeeTypeId = 5L,
                            CoffeeIngredientId = 1L,
                            Value = 60L
                        },
                        new
                        {
                            CoffeeTypeId = 5L,
                            CoffeeIngredientId = 2L,
                            Value = 120L
                        });
                });

            modelBuilder.Entity("MyTestAppBack.Domain.Aggregates.CoffeeIngredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("dictCoffeeIngredient");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsOptional = false,
                            Name = "Эспрессо"
                        },
                        new
                        {
                            Id = 2L,
                            IsOptional = false,
                            Name = "Вода"
                        },
                        new
                        {
                            Id = 3L,
                            IsOptional = false,
                            Name = "Молоко"
                        },
                        new
                        {
                            Id = 4L,
                            IsOptional = true,
                            Name = "Сливки"
                        },
                        new
                        {
                            Id = 5L,
                            IsOptional = true,
                            Name = "Сахар"
                        },
                        new
                        {
                            Id = 6L,
                            IsOptional = true,
                            Name = "Взбитые сливки"
                        },
                        new
                        {
                            Id = 7L,
                            IsOptional = true,
                            Name = "Мороженое"
                        },
                        new
                        {
                            Id = 8L,
                            IsOptional = true,
                            Name = "Тертый шоколад"
                        },
                        new
                        {
                            Id = 9L,
                            IsOptional = true,
                            Name = "Лимон"
                        },
                        new
                        {
                            Id = 10L,
                            IsOptional = true,
                            Name = "Молотый орех"
                        },
                        new
                        {
                            Id = 11L,
                            IsOptional = true,
                            Name = "Виски"
                        },
                        new
                        {
                            Id = 12L,
                            IsOptional = true,
                            Name = "Мед"
                        },
                        new
                        {
                            Id = 13L,
                            IsOptional = true,
                            Name = "Коньяк"
                        },
                        new
                        {
                            Id = 14L,
                            IsOptional = true,
                            Name = "Ликер"
                        },
                        new
                        {
                            Id = 15L,
                            IsOptional = true,
                            Name = "Корица"
                        },
                        new
                        {
                            Id = 16L,
                            IsOptional = false,
                            Name = "Вспененное молоко"
                        },
                        new
                        {
                            Id = 17L,
                            IsOptional = true,
                            Name = "Карамель"
                        });
                });

            modelBuilder.Entity("MyTestAppBack.Domain.Aggregates.CoffeeSyrup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CoffeeSyrups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Сироп BARINOFF \"Соленая карамель\" обладает аппетитной густой консистенцией и покоряет мягкими нюансами карамели и ванили",
                            Name = "Карамель"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Сироп Амаретто – безалкогольный вариант традиционного миндального ликера, обладающий богатым вкусом, красивым золотистым оттенком",
                            Name = "Амаретто"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Сироп «Лесной орех» имеет желтовато-оливковый оттенок, насыщенный аромат фундука и маслянистый, дымчатый вкус натуральных лесных орехов",
                            Name = "Лесной орех"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Шоколодный сироп для кофе - не канон",
                            Name = "Шоколад"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Сироп «Соленая карамель» обладает сильным, глубоким и ярким ароматом солоноватой карамели",
                            Name = "Соленая карамель"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Мммм (^^)",
                            Name = "Кокос"
                        });
                });

            modelBuilder.Entity("MyTestAppBack.Domain.Aggregates.CoffeeType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("dictCoffeeType");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Как появился этот вид кофе? Во время Второй мировой войны американские солдаты искали в Италии свой традиционный фильтр-кофе, поэтому итальянские бариста решили разбавить эспрессо, в результате чего получился совершенно новый напиток.",
                            Name = "Эспрессо"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Двойная порция эспрессо",
                            Name = "Доппио"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Эспрессо с увеличенным количеством воды",
                            Name = "Лунго"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Многие считают, что в ристретто слишком много кофеина, но это заблуждение. Первые несколько секунд заваривания из кофе выделяются эфирные масла, придающие ему насыщенный вкус, а кофеин поступает в напиток позднее. Из-за этого в ристретто обычно даже меньше кофеина, чем в эспрессо.",
                            Name = "Ристретто"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Эспрессо, разбавленный кипятком в пропорции 1:2 или 1:3",
                            Name = "Американо"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Двойная порция эспрессо, куда добавляют немного горячего молока с пеной",
                            Name = "Флэт уайт"
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Слово «макиато» с итальянского переводится как «пятнышко». Такое кофейное темное пятнышко образуется сверху на молочной пене после вливания эспрессо в горячее молоко.",
                            Name = "Макиато"
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Капучино в переводе с итальянского означает «капуцинский», так как его придумали монахи-капуцины. Основная составляющая капучино - это эспрессо, вторая – молоко.",
                            Name = "Капучино"
                        },
                        new
                        {
                            Id = 9L,
                            Description = "Название итальянского кофе латте в переводе означает «кофе с молоком». Как и следует из названия, основными составляющими этого напитка являются эспрессо и молоко.",
                            Name = "Латте"
                        },
                        new
                        {
                            Id = 10L,
                            Description = "Охлаждённый кофе с шариком мороженого. Напиток подают в айриш-бокале с соломинкой",
                            Name = "Глясе"
                        },
                        new
                        {
                            Id = 11L,
                            Description = "Коктейль (по сути, пена) из эспрессо со сливками и ванильным сахаром, взбитого в капучинаторе",
                            Name = "Раф"
                        },
                        new
                        {
                            Id = 13L,
                            Description = "Во вкусе мокко больше преобладает шоколадно-сливочный аромат, чем кофейный. А температура готового напитка не очень высокая, так как сироп и сливки добавляются в мокко холодными.",
                            Name = "Мокко"
                        },
                        new
                        {
                            Id = 14L,
                            Description = "Кофе по-турински, состоящий из 3 слоёв: горячего шоколада на молоке, эспрессо и взбитых сливок. Сверху кофе украшают тёртым горьким шоколадом и мятой",
                            Name = "Бичерин"
                        });
                });

            modelBuilder.Entity("MyTestAppBack.Domain.Aggregates.CoffeeComposition", b =>
                {
                    b.HasOne("MyTestAppBack.Domain.Aggregates.CoffeeIngredient", "CoffeeIngredient")
                        .WithMany("CoffeeCompositions")
                        .HasForeignKey("CoffeeIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyTestAppBack.Domain.Aggregates.CoffeeType", "CoffeeType")
                        .WithMany("CoffeeCompositions")
                        .HasForeignKey("CoffeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoffeeIngredient");

                    b.Navigation("CoffeeType");
                });

            modelBuilder.Entity("MyTestAppBack.Domain.Aggregates.CoffeeIngredient", b =>
                {
                    b.Navigation("CoffeeCompositions");
                });

            modelBuilder.Entity("MyTestAppBack.Domain.Aggregates.CoffeeType", b =>
                {
                    b.Navigation("CoffeeCompositions");
                });
#pragma warning restore 612, 618
        }
    }
}
