version: '3'

services:
  frontend:
    build: ./my-test-app-front
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./MyTestAppBack
    restart: always
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: myStrongPassword!
    ports:
      - "1433:1433"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"
    depends_on:
      - db